spring.application.name=Personal-Blog
server.port=8080

blog.storage.path=./data/articles

admin.username=admin
# BCrypt hash of "admin123" - change this for real deployment
admin.password-hash=$2a$10$QS0.d0lVO2ZrIRDKNnVgueVHKOHo7Sxp7yplmeFGoqo3rhSQqPOBq
